<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="YesSql" Version="5.4.1" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' != 'net8.0'">
    <PackageVersion Include="AspNet.Security.OAuth.GitHub" Version="9.4.0" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net8.0'">
    <PackageVersion Include="AspNet.Security.OAuth.GitHub" Version="8.3.0" />
  </ItemGroup>
</Project>